import { Link } from '@tanstack/react-router';
import { useState, useEffect } from 'react';
import { Menu, X, ArrowUp } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { assets } from '@/lib/site-assets';
const sections: [string, string][]=[['About Us','ABOUT-US'],['Our Products','OUR-PRODUCTS'],['Production and Global Sourcing','PRODUCTION-AND-GLOBAL-SOURCING'],['Global Market Reach','GLOBAL-MARKET-REACH']];
export function SiteHeader() {const [open,setOpen]=useState(false);useEffect(()=>{if(!open)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);};document.addEventListener('keydown',close);const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',close);document.body.style.overflow=old;};},[open]);const links=<><Link to="/" onClick={()=>setOpen(false)}>Home</Link>{sections.map(([label,hash])=><Link key={hash} to="/" hash={hash} onClick={()=>setOpen(false)}>{label}</Link>)}<Link to="/contact-us" onClick={()=>setOpen(false)}>Contact Us</Link></>;return <header className="site-header"><Link to="/" aria-label="Genesis Exotics home"><img className="site-logo" src={assets.logo} alt="Genesis Exotics"/></Link><nav className="desktop-nav" aria-label="Main navigation">{links}</nav><Button variant="ghost" size="icon" className="menu-trigger" aria-label="Open menu" aria-expanded={open} onClick={()=>setOpen(true)}><Menu/></Button>{open&&<nav className="mobile-nav" aria-label="Mobile navigation"><Button variant="ghost" size="icon" className="menu-close" aria-label="Close menu" onClick={()=>setOpen(false)}><X/></Button>{links}</nav>}</header>;}
export function SiteFooter(){return <footer className="site-footer"><div className="footer-layout"><Link to="/" aria-label="Genesis Exotics home"><img className="footer-logo" src={assets.footerLogo} alt="Genesis Exotics, Produce Box and Dee Zed" loading="lazy"/></Link><div><h3>Quick Links</h3>{sections.slice(0,3).map(([label,hash])=><Link key={hash} to="/" hash={hash}>{label}</Link>)}<Link to="/privacy-policy">Privacy Policy</Link><Link to="/terms-and-conditions">Terms and Conditions</Link><Link to="/cookie-policy">Cookie Policy</Link></div><div><h3>Our Products</h3>{['Mangetout Peas','Sugar Snap Peas','Fine Beans/Haricots','Chillies','Baby Vegetables','Passion Fruit'].map(p=><p key={p}>{p}</p>)}</div><div><h3>Contact Information</h3><p>2 Greenway Parade<br/>Chesham – HP5 2DA<br/>Buckinghamshire<br/>United Kingdom</p><a href="tel:+447471312213">+44 7471 312213</a><a href="tel:+447394507367">+44 7394 507367</a>{['lovemore','sales','admin'].map(n=><a key={n} href={`mailto:${n}@genesis-exotics.co.uk`}>{n}@genesis-exotics.co.uk</a>)}</div></div></footer>;}
export function BackToTop(){const [visible,setVisible]=useState(false);useEffect(()=>{const update=()=>setVisible(window.scrollY>400);update();window.addEventListener('scroll',update,{passive:true});return()=>window.removeEventListener('scroll',update);},[]);return visible?<Button size="icon" className="back-top" aria-label="Back to top" title="Back to top" onClick={()=>window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}><ArrowUp/></Button>:null;}
