import { Link } from '@tanstack/react-router';
import { Button } from '@/components/ui/button';
import { assets } from '@/lib/site-assets';
export const products = [
 {name:'Mangetout Peas',description:'Crisp, tender and full of flavour',image:assets.mangetout},
 {name:'Sugar Snap Peas',description:'Sweet, crunchy and nutritious',image:assets.snapPeas},
 {name:'Fine Beans/Haricots Verts',description:'Fresh, tender and handpicked',image:assets.beans},
 {name:'Chillies',description:'Green and Red varieties',image:assets.chillies},
 {name:'Baby Vegetables',description:'Sweet, tender and perfect for every dish',image:assets.babyVegetables},
 {name:'Passion Fruit (Granadilla)',description:'Juicy, aromatic and naturally delicious',image:assets.passionFruit},
];
export function AboutSection() { return <section id="ABOUT-US" className="about-section"><div className="section-inner about-layout"><div className="about-copy"><p className="section-eyebrow">About Us</p><h2 className="section-heading">Your Trusted Global Produce Partner</h2><p className="section-copy">Genesis Exotics is a UK and international agri-business specialising in the production, sourcing and export of premium-quality fruits and vegetables.</p><p className="section-copy">With strong roots in Africa and strategic partnerships across the globe, we deliver excellence across every stage of the value chain.</p><Button asChild className="produce-button"><Link to="/" hash="OUR-PRODUCTS">Learn More About Us</Link></Button></div><div className="about-photos"><img className="peas-photo" src={assets.snapPeas} alt="Fresh sugar snap peas" loading="lazy"/><div className="about-photo-stack"><img src={assets.packing} alt="Genesis Exotics team preparing fresh produce" loading="lazy"/><img src={assets.boxedPeas} alt="Premium peas packed for export" loading="lazy"/></div></div></div></section>; }
export function FeaturesSection() { const features=[['Global Sourcing','Strategic partnerships in Africa, Europe and South America ensure year-round supply.',assets.globalSourcing],['Certified Quality','Global G.A.P., SMETA, HACCP and BRC certified for food safety and quality assurance.',assets.quality],['Sustainability','Committed to environmentally responsible practices for a better future.',assets.sustainability],['Reliable Logistics','Efficient cold chain and global logistics delivering freshness, every time.',assets.logistics]];return <section><div className="section-inner features-layout">{features.map(([title,copy,image])=><div className="feature" key={title}><img src={image} alt="" loading="lazy"/><h3>{title}</h3><p>{copy}</p></div>)}</div></section>; }
export function ProductsSection() { return <section id="OUR-PRODUCTS" className="products-section"><div className="section-inner"><div className="section-centered"><p className="section-eyebrow">Our Products</p><h2 className="section-heading">Premium Produce. Exceptional Quality.</h2><p className="section-copy">We grow and source a wide range of fresh fruits and vegetables with care,<br/>ensuring premium quality and consistent supply all year round.</p></div><div className="product-grid">{products.map(p=><article className="product-item" key={p.name}><img src={p.image} alt={p.name} loading="lazy"/><h3>{p.name}</h3><p>{p.description}</p></article>)}</div></div></section>; }
export function SourcingSection() { return <section id="PRODUCTION-AND-GLOBAL-SOURCING"><div className="section-inner sourcing-layout"><div className="sourcing-copy"><p className="section-eyebrow">Production &amp; Global Sourcing</p><h2 className="section-heading">From Our Farms<br/>To The World</h2><p className="section-copy">We work with our own farms and trusted partners across key regions to deliver consistent quality and freshness all year long.</p><img className="countries-image" src={assets.countries} alt="Zimbabwe, Egypt, Kenya, Peru, Guatemala, Rwanda and South Africa" loading="lazy"/></div><div className="sourcing-farm"><img src={assets.farm} alt="Peas growing on our farms" loading="lazy"/></div><div className="sourcing-regions"><img src={assets.regionHeading} alt="Our Sourcing Regions" loading="lazy"/><img src={assets.regions} alt="Year-round sourcing partnerships across Africa and South America" loading="lazy"/></div></div></section>; }
export function MarketsSection() { return <section id="GLOBAL-MARKET-REACH" className="market-section"><div className="section-inner"><div className="market-layout"><div className="market-copy"><p className="section-eyebrow">Global Market Reach</p><h2 className="section-heading">Connecting Continents,<br/>Delivering Freshness</h2><p className="section-copy">We work with our premium-quality produce to wholesalers, distributors, food service providers, retailers and export markets worldwide.</p></div><img className="market-map" src={assets.markets} alt="Our key markets and global logistics hubs" loading="lazy"/></div><div className="market-benefits"><img src={assets.supply} alt="Reliable supply, global standards, strategic partnerships and competitive advantage" loading="lazy"/><img src={assets.serve} alt="Who we serve, UK registered, year-round delivery and sustainability focus" loading="lazy"/></div></div></section>; }
export function FutureBanner() { return <div className="future-banner"><img src={assets.future} alt="Let’s Build A Sustainable Future Together — Genesis Exotics" loading="lazy"/></div>; }
